linear regression

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [10]:
x=np.array([25,35,45,55,65,75])
y=np.array([5,20,14,32,22,38])

array([[ 5],
       [20],
       [14],
       [32],
       [22],
       [38]])

In [11]:
model=LinearRegression()

In [13]:
from sklearn.linear_model import LinearRegression
import numpy as np

x = np.array([25, 35, 45, 55, 65, 75]).reshape(-1, 1)  # Reshaping x to a column vector
y = np.array([5, 20, 14, 32, 22, 38])

# Creating a LinearRegression model
model = LinearRegression()

# Fitting the model to your data
model.fit(x, y)


LinearRegression()

In [15]:
r_sq_score=model.score(x,y)
r_sq_score


0.7158756137479542

In [17]:
model.intercept_

-5.166666666666664

In [18]:
model.coef_

array([0.54])

In [19]:
model.predict(x)

array([ 8.33333333, 13.73333333, 19.13333333, 24.53333333, 29.93333333,
       35.33333333])

In [20]:
y

array([ 5, 20, 14, 32, 22, 38])

multi linear regression

In [40]:
x1=[[10,21],[5,18],[15,24],[25,56],[35,11],[55,11],[55,34],[90,35]]
y1=[4,14,15,20,14,32,22,38]

In [41]:
print(x1)
print(y1)

[[10, 21], [5, 18], [15, 24], [25, 56], [35, 11], [55, 11], [55, 34], [90, 35]]
[4, 14, 15, 20, 14, 32, 22, 38]


In [42]:
x1=np.array(x1)
y1=np.array(y1)

In [43]:
x1

array([[10, 21],
       [ 5, 18],
       [15, 24],
       [25, 56],
       [35, 11],
       [55, 11],
       [55, 34],
       [90, 35]])

In [44]:
y1

array([ 4, 14, 15, 20, 14, 32, 22, 38])

In [45]:
from sklearn.linear_model import LinearRegression
import numpy as np


model1= LinearRegression()

# Fitting the model to your data
model1.fit(x1, y1)


LinearRegression()

In [46]:
r_sq_scor=model1.score(x1,y1)
r_sq_scor


0.7948990611663358

In [47]:
model1.intercept_

6.651799982887544

In [48]:
y1


array([ 4, 14, 15, 20, 14, 32, 22, 38])

In [49]:
model1.predict(x1)

array([10.94976526,  9.1552073 , 12.74432322, 17.56211135, 18.74113947,
       25.35229183, 26.43919417, 38.05596742])

In [50]:
y1

array([ 4, 14, 15, 20, 14, 32, 22, 38])